### ISSUE TITLE
ECC does not work on IE

### ISSUE THREAD

**Issue by rmhrisk** [PeculiarVentures/webcrypto-liner#15]
We have been unable to get ECC to work in IE, Elliptic js goes into an infinite loop. Need to find out why and fix.

**Comment by rmhrisk** [comment]
More specifically it seems everything works except for export key which loops for some reason.

**Comment by yuhong** [comment]
See if you can use Process Explorer or WinDbg to get a call stack.

**Comment by rmhrisk** [comment]
@yuhong so you think it's a big in the js runtime vs elliptic or our use of it?

**Comment by indutny** [comment]
If anyone has access to IE and is willing to test it - we can try to bisect the problem.

First suggestion would be to add `throw 1` at the top of:

https://github.com/indutny/elliptic/blob/master/lib/elliptic/curve/short.js#L423

And see if it crashes. (If it is not - the problem happens earlier).

----

Alternatively, it may be looping in https://github.com/indutny/elliptic/blob/master/lib/elliptic/ec/index.js#L116-L148 , but it sounds unlikely.

**Comment by rmhrisk** [comment]
Fixed

**Comment by indutny** [comment]
@rmhrisk mind sharing some details? 😉
