### ISSUE TITLE
Download version

### ISSUE THREAD

**Issue by fletchgqc** [PeculiarVentures/webcrypto-liner#19]
Could you please make a built version available so that I don't have to do that myself?

**Comment by microshine** [comment]
You can take last compiled vesion from [pv-webcrypto-tests](https://github.com/PeculiarVentures/pv-webcrypto-tests/tree/gh-pages/src)

**Comment by microshine** [comment]
And test app on [gh-pages](https://peculiarventures.github.io/pv-webcrypto-tests/)

**Comment by rmhrisk** [comment]
We publish a npm module, that is really the right way to do this.

You dont want to do crypto with JS hosted by someone else.

Closing
