### ISSUE TITLE
Test execution time is very long in Safari

### ISSUE THREAD

**Issue by rmhrisk** [PeculiarVentures/webcrypto-liner#36]
![image](https://cloud.githubusercontent.com/assets/1619279/25400480/997a51b8-29a7-11e7-9c92-d7d3a9f951b8.png)

**Comment by rmhrisk** [comment]
I think this is probably because we are using JS when we could be using the new native capabilities

**Comment by microshine** [comment]
There is no `elliptic.js` in index.html file

Old version of `webcrypto-liner` had elliptic.js in it

**Comment by microshine** [comment]
@rmhrisk pv-webcrypto-tests on gh-pages are updated
