### ISSUE TITLE
Init failed on Safari 602.1

### ISSUE THREAD

**Issue by WorldThirteen** [PeculiarVentures/webcrypto-liner#37]
Liner is failed to init on IOS Safari 602.1
Next used regular expression returns `null`
```js
/([\d\.]+) safari/i.exec(userAgent)[1];
```
and getting [1] throws an exception:
`TypeError: null is not an object (evaluating '/([\\d\\.]+) safari/i.exec(userAgent)[1]')`

User agent: 
```
Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like Mac OS X) AppleWebKit/603.2.3 (KHTML, like Gecko) Version/10.0 Mobile/14F5080a Safari/602.1
```

**Comment by microshine** [comment]
@WorldThirteen Could you check last update?

**Comment by WorldThirteen** [comment]
@microshine, sure, I will notify at the nearest time.

**Comment by WorldThirteen** [comment]
Fixed.
last notice before closing: should next files also be changed?
https://github.com/PeculiarVentures/webcrypto-liner/blob/master/scripts/linerBrowserInit.js#L39
https://github.com/PeculiarVentures/webcrypto-liner/blob/master/scripts/linerWorkerInit.js#L39

**Comment by microshine** [comment]
thank you. I forgot about those files
