### ISSUE TITLE
Can not call "importKey" for AES-ECB algorithm

### ISSUE THREAD

**Issue by YuryStrozhevsky** [PeculiarVentures/webcrypto-liner#41]

**Comment by rmhrisk** [comment]
@YuryStrozhevsky can you provide more detail?

@microshine please investigate

**Comment by rmhrisk** [comment]
Sounds like there is no importKey() implemented, @microshine please resolve ASAP.

**Comment by microshine** [comment]
@YuryStrozhevsky Could you provide more detail?

This code works
```js
//@ts-check
var alg = {
    name: "AES-ECB",
    length: 256,
};
var format = "raw";
crypto.subtle.generateKey(alg, true, ["encrypt", "decrypt"])
    .then((key) => {
        console.log(key.key);
        return crypto.subtle.exportKey(format, key)
    })
    .then((raw) => {
        return crypto.subtle.importKey(format, raw, alg, true, ["encrypt", "decrypt"]);
    })
    .then((key) => {
        console.log(key.key);
    });
```

![image](https://user-images.githubusercontent.com/7333669/33654224-820778c8-da80-11e7-92c9-d6b8c3dc0692.png)

**Comment by YuryStrozhevsky** [comment]
@microshine This code does not work:
```javascript
crypto.importKey("raw",key, { name: "AES-ECB" }, false, ["decrypt"])
```

**Comment by microshine** [comment]
I tried
```js
crypto.subtle.importKey("raw",key, { name: "AES-ECB" }, false, ["decrypt"])
crypto.subtle.importKey("raw",key, "AES-ECB", false, ["decrypt"])
crypto.subtle.importKey("raw",key, "aes-ecb", false, ["decrypt"])
```

![image](https://user-images.githubusercontent.com/7333669/33655106-41482bc2-da83-11e7-9e9e-45c11d569ed4.png)

**Comment by YuryStrozhevsky** [comment]
@microshine I did not understand your last comment: it is confirming my problem or your are saying I done something wrong?

**Comment by microshine** [comment]
@YuryStrozhevsky I don't have error on `crypto.subtle.importKey`. Send me all incoming params to reproduce this error

**Comment by YuryStrozhevsky** [comment]
@microshine Hmm, I can see on your screenshot exactly the same message:
```
WebCrypto: native 'importKey' for AES-ECB doesn't work. Algorithm: Unrecognized name
```

**Comment by microshine** [comment]
This is warning for native crypto usage

**Comment by YuryStrozhevsky** [comment]
@microshine So how to fix it?

**Comment by microshine** [comment]
Do you want to remove this log?

**Comment by YuryStrozhevsky** [comment]
@microshine So this is not an error but warning? And the key imported successfully?

**Comment by YuryStrozhevsky** [comment]
@microshine OK, then I close this issue. Instead I need a solution for [this issue](https://github.com/PeculiarVentures/webcrypto-liner/issues/42): before I thought my code is not working because of import but seems it is because of "padding issue".
