### ISSUE TITLE
Update to the latest asmcrypto.js

### ISSUE THREAD

**Issue by jeremyVignelles** [PeculiarVentures/webcrypto-liner#47]
asmcrypto.js seems to have made a few breaking changes in the latest versions, making the default "npm install" broken.

Could you please update your project?

**Comment by microshine** [comment]
There is another WebCrypto module in npm - [node-webcrypto-ossl](https://www.npmjs.com/package/node-webcrypto-ossl). It has native implementation and works faster than JS.

**Comment by microshine** [comment]
`webcrypto-liner` uses fixed version of `asmcrypto.js` 
https://github.com/PeculiarVentures/webcrypto-liner/blob/master/package.json#L20

I checked `npm install webcrypto-liner`. It works

**Comment by jeremyVignelles** [comment]
I was having undefined references to asmcrypto... weird... Probably something wrong on my side.

**Comment by Jack-Works** [comment]
TypeError: Cannot read property 'bytes' of undefined

      at Function.digest (node_modules/webcrypto-liner/build/webcrypto-liner.shim.js:10503:19)   
      at Sha256Provider.onDigest (node_modules/webcrypto-liner/build/webcrypto-liner.shim.js:10516:24)
      at Sha256Provider.<anonymous> (node_modules/webcrypto-liner/build/webcrypto-liner.shim.js:403:30)

When using the asmcrypto lib on npm. `require('asmcrypto.js/asmcrypto.all.es8')`

**Comment by Jack-Works** [comment]
Including a fixed(compressed) version of asmcrypto will make us can not pass the security audit, please publish a forked version of asmcrypto that will work with webcrypto-liner thanks!

**Comment by microshine** [comment]
Please try
```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/asmCrypto/2.3.2/asmcrypto.all.es5.min.js"></script>
```

**Comment by Jack-Works** [comment]
> Please try
> 
> ```
> <script src="https://cdnjs.cloudflare.com/ajax/libs/asmCrypto/2.3.2/asmcrypto.all.es5.min.js"></script>
> ```

I'm writing test for the project so the code is running in the node. And you said web-crypto liner is using a "fixed" version of asmcrypto. I have tried the official asmcrypto package, it doesn't work well with the liner
