### ISSUE TITLE
Cannot export RSA-OAEP key on iOS 10 Safari

### ISSUE THREAD

**Issue by doraemondrian** [PeculiarVentures/webcrypto-liner#53]
I took the same example over at https://github.com/PeculiarVentures/webcrypto-liner/issues/50 and just switched the AES-GCM algorithm to RSA-OAEP, and that seems to break the example.

By the way I can confirm that the original example (after the fix at https://github.com/PeculiarVentures/webcrypto-liner/issues/50#issuecomment-363374774) works just fine.

It just doesn't work for RSA-OAEP export.

Here's the code (Pretty much the same, except I'm trying to export an RSA key)

```html
<HTML>
<head>
    <meta charset="UTF-8">
    <title>WebCrypto Liner</title>
    <script src="https://microshine.github.io/test-webcrypto/webcrypto-liner.shim.js"></script>
    <script src="https://microshine.github.io/test-webcrypto/asmcrypto.min.js"></script>
</head>

<body>
    <script>
        function test2() {
            crypto.subtle.generateKey(
              {
                name: "RSA-OAEP",
                modulusLength: 2048,
                publicExponent: new Uint8Array([0x01, 0x00, 0x01]),
                hash: {name: "SHA-256"},
              },
              true,
              ["encrypt", "decrypt"]
            ).then(function(key) {
              console.log("key = ", key);
              return crypto.subtle.exportKey("jwk", key.publicKey)
            }).catch(function (err) {
                console.error("Y3 error: ", err);
                write_debug("Y3 error: " + err);
            }).then(function (keydata) {
                console.log("Y4");
                write_debug("Y4");
            })
        }
        function write_debug(txt) {
            var div = document.createElement("div");
            document.body.appendChild(div);
            div.innerHTML = txt;
        }
        test2();
    </script>
</BODY>
</HTML>
```

I get an `"Y3 error: Error: Cannot export native CryptoKey from JS implementation"`.

I'm using iOS 10 safari on an iPad. (It works fine on other browsers)

**Comment by microshine** [comment]
This is because Safari can generate RSA-OAEP but have error on `exportKey`
I added alert on error in native exportKey. Here is screen with error message.
![img_2884](https://user-images.githubusercontent.com/7333669/36015145-48c442a4-0d7e-11e8-8f95-fd70934b1e5f.PNG)

We can replace native `generateKey` for `RSA-OAEP` and use JS implementation for it.
@rmhrisk What do you think about it?

**Comment by rmhrisk** [comment]
If I understand correctly the issue is Safari, or this version, does not allow exporting if the public key for RSA-OAEP?

This seems pretty fundamental, isn’t there a a chance we have to make this call in a different way in the case if Safari?

Does WebCrypto-tests have the same behavior?

**Comment by rmhrisk** [comment]
Sounds like Safari 11 works but this version does not.

If so then yes using JS is the right solution but only for those older than 11.

**Comment by doraemondrian** [comment]
Yes, I can confirm it works on iOS 11

In fact the reason I started researching an alternative to the native WebCrypto api in the first place was because my app which works perfectly fine on iOS 11 suddenly stopped working on iOS 10. 

This meant I can't use native webcrypto for exporting, so I started looking and i came across this project.

**Comment by microshine** [comment]
@doraemondrian Can you try https://microshine.github.io/test-webcrypto/ on Safari v10 and v11?
I uploaded test lib with alert dialogs in it

**Comment by doraemondrian** [comment]
@microshine here it is:

## iOS 10 on iPad

- RSA-OAEP JS
- Throws an error

![img_0019 2](https://user-images.githubusercontent.com/33023863/36018116-674061da-0d2f-11e8-8973-e771557a1b26.PNG)

![img_0020](https://user-images.githubusercontent.com/33023863/36018069-2f515a68-0d2f-11e8-93a4-5bbcce489424.PNG)


## iOS 11 on iPhone

- RSA-OAEP native
- Works

![img_0153](https://user-images.githubusercontent.com/33023863/36018090-4612307e-0d2f-11e8-8352-366aa261bc6e.JPG)

**Comment by microshine** [comment]
@doraemondrian `Type error` is from `exportKey` because CryptoKey is not native. It's ok

I'll update importKey for RSA-OAEP and publish new version

**Comment by doraemondrian** [comment]
Thanks! Looking forward to it!

**Comment by doraemondrian** [comment]
Just checked and looks like it's working, thank you!

<img width="1310" alt="screen shot 2018-02-09 at 1 14 31 am" src="https://user-images.githubusercontent.com/33023863/36020194-a9528394-0d36-11e8-8aff-52b04bdca6e1.png">
