### ISSUE TITLE
iphonese  ios: 9.3.5 can't worked

### ISSUE THREAD

**Issue by cqupt-yifanwu** [PeculiarVentures/webcrypto-liner#73]
I uesed ECDH 

``` javascript
    const {publicKey, privateKey} = await crypto.subtle.generateKey(
        {
            name: "ECDH",
            namedCurve: "P-256",
        },
        false,
        ["deriveKey", "deriveBits"]
    );
```
i trans it to es3.
does this has compatibility report, or only ecdh' compatibility in mobile phone(ios & Android)，

**Comment by cqupt-yifanwu** [comment]
![image](https://user-images.githubusercontent.com/13469100/71866909-eeaae080-3142-11ea-9f47-206f97dba452.png)

**Comment by rmhrisk** [comment]
Unfortunately we no longer have access to devices running 9.3.5. I believe we did work at this level at one point though.

Possibilities include:
1) issue with transpiration to es3 (probably relating to the associated polyfills)
2) changes to dependencies that have happened.

If you can resolve the issue we would accept a well thought out PR.

**Comment by microshine** [comment]
Please try this script. I compiled it using iOS9 target 
[webcrypto-liner.shim.js.txt](https://github.com/PeculiarVentures/webcrypto-liner/files/4029269/webcrypto-liner.shim.js.txt)

**Comment by cqupt-yifanwu** [comment]
> Please try this script. I compiled it using iOS9 target
> [webcrypto-liner.shim.js.txt](https://github.com/PeculiarVentures/webcrypto-liner/files/4029269/webcrypto-liner.shim.js.txt)

![image](https://user-images.githubusercontent.com/13469100/71886612-7f031880-3177-11ea-8d84-c6314c1c19a9.png)
it is not worked to me 

and i used babel-ployfill transfer my project

**Comment by microshine** [comment]
Can you detect which line of `webcrypto-liner` throws an exception?

and please check `window.liner.crypto.subtle.generateKey`. Maybe `webcrypto-liner` can't replace `winodos.crypto`

**Comment by cqupt-yifanwu** [comment]
window.liner is undefined, but crypto.subtle  is different with origin window.crypto.subtle
![image](https://user-images.githubusercontent.com/13469100/71890098-8bd73a80-317e-11ea-96ec-73af6265e7c8.png)
![image](https://user-images.githubusercontent.com/13469100/71890137-9a255680-317e-11ea-9217-5de12e551753.png)


the error throw in this line
![image](https://user-images.githubusercontent.com/13469100/71890242-d1940300-317e-11ea-8525-b32d3afc851d.png)
i has babeled this file, so it may not correct
![image](https://user-images.githubusercontent.com/13469100/71890242-d1940300-317e-11ea-8525-b32d3afc851d.png)

**Comment by microshine** [comment]
Is it possible to use `webcrypto-liner.shim.js` without adding it to a bundle file?

If you want to use `webrypto-liner` as ES6 module you can do it but you need to initialize your own `crypto` object

```js
import { Crypto } from "webcrypto-liner";

const crypto = new Crypto();
```

**Comment by cqupt-yifanwu** [comment]
hi @microshine 
i use webpack to Compile my code，and it worded in IE。i just want to run ecdh in lower version mobile phone like ios 9.3.5
![image](https://user-images.githubusercontent.com/13469100/71942527-79014c00-31f8-11ea-88b5-c882ba57b0ae.png)
![image](https://user-images.githubusercontent.com/13469100/71942598-b36ae900-31f8-11ea-87a1-e3577796d055.png)

**Comment by cqupt-yifanwu** [comment]
my test demo is:
https://github.com/cqupt-yifanwu/ecdh-demo

**Comment by cqupt-yifanwu** [comment]
> ```js
> import { Crypto } from "webcrypto-liner";
> 
> const crypto = new Crypto();
> ```

it is work for me...
