### ISSUE TITLE
Can't find elliptic js script

### ISSUE THREAD

**Issue by matan21197** [PeculiarVentures/webcrypto-liner#79]
when including both webcrypto-liner and elliptic js the following error is returned when trying to use ECDH functions: 
Unhandled Promise Rejection: Error: Cannot implement EC mechanism. Add 'https://peculiarventures.github.io/pv-webcrypto-tests/src/elliptic.js' script to your project.
 The error is returned when running on safari

**Comment by rmhrisk** [comment]
Please provide minimal example code to reproduce.

What uservagent?

**Comment by matan21197** [comment]
i am running from safari 13.1 on ios 13.5 and get the error when executing 
`await crypto.subtle.importKey(
        "jwk",
        key,
        {
            name: "ECDH",
            namedCurve: 'p-521'
        },
        false,
        []
    )`
the code works when including the elliptic.js script manually with a script tag, but i would like to import the js script, and when i do it outputs the error above

**Comment by rmhrisk** [comment]
Please provide minimal example code to reproduce.

**Comment by donskov** [comment]
Hello @matan21197 . I prepared for you example of how to use `webcrypto-liner` with `import`.


Install npm modules:

```bash
npm install asmcrypto.js elliptic webcrypto-liner
```

Import modules to your code (using dynamic imports):

```js
function isFirefox() {
  return /firefox/i.test(window.navigator.userAgent);
}

function isEdge() {
  return /edge\/([\d.]+)/i.test(window.navigator.userAgent);
}

function isIE() {
  return !!(window.document as any).documentMode;
}

if (isEdge() || isFirefox() || isIE()) {
  if (!window['asmCrypto']) {
    window['asmCrypto'] = await import('asmcrypto.js/asmcrypto.all.es8.js');
  }

  if (!window['elliptic']) {
    window['elliptic'] = (await import('elliptic/lib/elliptic.js')).default;
  }

  await import('webcrypto-liner/build/webcrypto-liner.shim.mjs');
}
```

This code works with our [web-components](https://fortifyapp.com/developers/docs/installation/web-component). Look, maybe you will be interested.

Thanks!

**Comment by matan21197** [comment]
@donskov Thank you so much!
The issue was fixed by adding:
`import * as elliptic from 'elliptic';

window['elliptic'] = elliptic`
Maybe it should be added to the readme that elliptic and asmCrypto need to be added to the window
Again, thank you very much
