### ISSUE TITLE
asmcrypto_js is undefined

### ISSUE THREAD

**Issue by alexeyorlove** [PeculiarVentures/webcrypto-liner#80]
Hey.
I am getting error in **webcrypto-liner.shim.mjs** because _asmcrypto_js is undefined_.

Because _self.asmCrypto_ is undefined too.

Although I am including both of these packages.
```
require ("asmcrypto.js")
require ("webcrypto-liner")
```

But if I connect like this, everything works. But it doesn't look right.
```
window.asmCrypto = require ("asmcrypto.js")
require ("webcrypto-liner")
```

How to use this polyfill correctly?
Thanks

**Comment by donskov** [comment]
@alexeyorlove Hello. Now `webcrypto-liner` uses the global `asnCrypto` object. Please look at https://github.com/PeculiarVentures/webcrypto-liner/issues/79#issuecomment-668453929

**Comment by alexeyorlove** [comment]
@donskov thanks!
